using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.Player;

namespace Content.Client.Info.UUID;

[GenerateTypedNameReferences]
public sealed partial class UUIDWindow : DefaultWindow
{
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IClipboardManager _clipboard = default!;

    public UUIDWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var session = _player.LocalSession;
        var uid = session?.UserId;
        var name = session?.Name;

        if (session == null || !uid.HasValue)
        {
            UsernameField.Text = "Błąd wczytywania lokalnych danych";
            UUIDField.Visible = false;
            CopyUUID.Visible = false;
            return;
        }

        UsernameField.Text = name != null
            ? $"{name}: "
            : string.Empty;
        UUIDField.Text = uid.Value.ToString();
        UUIDField.FontColorOverride = Color.GreenYellow;
        CopyUUID.OnPressed += _ => _clipboard.SetText(uid.Value.ToString());
    }
}
